export default [
    {
        code: "ski",
        moji: "🎿",
        unicode: "1f3bf",
        category: "objects",
        tags: [],
        link: null,
        base: "ski",
        variants: ["ski"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "heart eyes cat",
        moji: "😻",
        unicode: "1f63b",
        category: "faces",
        tags: [],
        link: null,
        base: "heart_eyes_cat",
        variants: ["heart_eyes_cat"],
        score: 17,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "crying cat face",
        moji: "😿",
        unicode: "1f63f",
        category: "faces",
        tags: [],
        link: null,
        base: "crying_cat_face",
        variants: ["crying_cat_face"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "raising hand",
        moji: "🙋",
        unicode: "1f64b",
        category: "gestures",
        tags: [],
        link: null,
        base: "raising_hand",
        variants: [
            "raising_hand(wh)",
            "raising_hand(p)",
            "raising_hand(ye)",
            "raising_hand(br)",
            "raising_hand(bk)",
            "raising_hand",
        ],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "raised hands",
        moji: "🙌",
        unicode: "1f64c",
        category: "gestures",
        tags: [],
        link: null,
        base: "raised_hands",
        variants: [
            "raised_hands(wh)",
            "raised_hands(p)",
            "raised_hands(ye)",
            "raised_hands(br)",
            "raised_hands(bk)",
            "raised_hands",
        ],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "helicopter",
        moji: "🚁",
        unicode: "1f681",
        category: "transportation",
        tags: [],
        link: null,
        base: "helicopter",
        variants: ["helicopter"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "runner",
        moji: "🏃",
        unicode: "1f3c3",
        category: "people",
        tags: [],
        link: null,
        base: "runner",
        variants: [
            "runner(wh)",
            "runner(ye)",
            "runner(br)",
            "runner(bk)",
            "runner",
            "runner(p)",
        ],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "label",
        moji: "🏷",
        unicode: "1f3f7",
        category: "objects",
        tags: [],
        link: null,
        base: "label",
        variants: ["label"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "nose",
        moji: "👃",
        unicode: "1f443",
        category: "people",
        tags: [],
        link: null,
        base: "nose",
        variants: [
            "nose",
            "nose(wh)",
            "nose(ye)",
            "nose(br)",
            "nose(bk)",
            "nose(p)",
        ],
        score: 1,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "lips",
        moji: "🗢",
        unicode: "1f5e2",
        category: "people",
        tags: [],
        link: null,
        base: "lips",
        variants: ["lips"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "crown",
        moji: "👑",
        unicode: "1f451",
        category: "objects",
        tags: [],
        link: null,
        base: "crown",
        variants: ["crown"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "shirt",
        moji: "👕",
        unicode: "1f455",
        category: "objects",
        tags: [],
        link: null,
        base: "shirt",
        variants: ["shirt"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "jeans",
        moji: "👖",
        unicode: "1f456",
        category: "objects",
        tags: [],
        link: null,
        base: "jeans",
        variants: ["jeans"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "dress",
        moji: "👗",
        unicode: "1f457",
        category: "objects",
        tags: [],
        link: null,
        base: "dress",
        variants: ["dress"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "purse",
        moji: "👛",
        unicode: "1f45b",
        category: "objects",
        tags: [],
        link: null,
        base: "purse",
        variants: ["purse"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "pouch",
        moji: "👝",
        unicode: "1f45d",
        category: "objects",
        tags: [],
        link: null,
        base: "pouch",
        variants: ["pouch"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "boot",
        moji: "👢",
        unicode: "1f462",
        category: "objects",
        tags: [],
        link: null,
        base: "boot",
        variants: ["boot"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "boy",
        moji: "👦",
        unicode: "1f466",
        category: "people",
        tags: [],
        link: null,
        base: "boy",
        variants: ["boy(wh)", "boy(p)", "boy(ye)", "boy(br)", "boy(bk)", "boy"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "girl",
        moji: "👧",
        unicode: "1f467",
        category: "people",
        tags: [],
        link: null,
        base: "girl",
        variants: [
            "girl(wh)",
            "girl(p)",
            "girl(ye)",
            "girl(br)",
            "girl(bk)",
            "girl",
        ],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "baby",
        moji: "👶",
        unicode: "1f476",
        category: "people",
        tags: [],
        link: null,
        base: "baby",
        variants: [
            "baby(wh)",
            "baby(p)",
            "baby(ye)",
            "baby(br)",
            "baby(bk)",
            "baby",
        ],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "ghost",
        moji: "👻",
        unicode: "1f47b",
        category: "people",
        tags: [],
        link: null,
        base: "ghost",
        variants: ["ghost"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "angel",
        moji: "👼",
        unicode: "1f47c",
        category: "people",
        tags: [],
        link: null,
        base: "angel",
        variants: [
            "angel(wh)",
            "angel(p)",
            "angel(ye)",
            "angel(br)",
            "angel(bk)",
            "angel",
        ],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "alien",
        moji: "👽",
        unicode: "1f47d",
        category: "people",
        tags: [],
        link: null,
        base: "alien",
        variants: ["alien"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "skull",
        moji: "💀",
        unicode: "1f480",
        category: "people",
        tags: [],
        link: null,
        base: "skull",
        variants: ["skull"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "pill",
        moji: "💊",
        unicode: "1f48a",
        category: "objects",
        tags: [],
        link: null,
        base: "pill",
        variants: ["pill"],
        score: 116,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "ring",
        moji: "💍",
        unicode: "1f48d",
        category: "objects",
        tags: [],
        link: null,
        base: "ring",
        variants: ["ring"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "gem",
        moji: "💎",
        unicode: "1f48e",
        category: "objects",
        tags: [],
        link: null,
        base: "gem",
        variants: ["gem(gr)", "gem(bl)", "gem"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "yen",
        moji: "💴",
        unicode: "1f4b4",
        category: "objects",
        tags: [],
        link: null,
        base: "yen",
        variants: ["yen"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "euro",
        moji: "💶",
        unicode: "1f4b6",
        category: "objects",
        tags: [],
        link: null,
        base: "euro",
        variants: ["euro"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "pound",
        moji: "💷",
        unicode: "1f4b7",
        category: "objects",
        tags: [],
        link: null,
        base: "pound",
        variants: ["pound"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "seat",
        moji: "💺",
        unicode: "1f4ba",
        category: "objects",
        tags: [],
        link: null,
        base: "seat",
        variants: ["seat"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "dvd",
        moji: "📀",
        unicode: "1f4c0",
        category: "objects",
        tags: [],
        link: null,
        base: "dvd",
        variants: ["dvd"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "date",
        moji: "📅",
        unicode: "1f4c5",
        category: "objects",
        tags: [],
        link: null,
        base: "date",
        variants: ["date"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "notebook with decorative cover",
        moji: "📔",
        unicode: "1f4d4",
        category: "objects",
        tags: [],
        link: null,
        base: "notebook_with_decorative_cover",
        variants: ["notebook_with_decorative_cover"],
        score: 1,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "book",
        moji: "📖",
        unicode: "1f4d6",
        category: "objects",
        tags: [],
        link: null,
        base: "book",
        variants: ["book"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "books",
        moji: "📚",
        unicode: "1f4da",
        category: "objects",
        tags: [],
        link: null,
        base: "books",
        variants: ["books"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "pager",
        moji: "📟",
        unicode: "1f4df",
        category: "objects",
        tags: [],
        link: null,
        base: "pager",
        variants: ["pager"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "fax",
        moji: "📠",
        unicode: "1f4e0",
        category: "objects",
        tags: [],
        link: null,
        base: "fax",
        variants: ["fax"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "mega",
        moji: "📣",
        unicode: "1f4e3",
        category: "objects",
        tags: [],
        link: null,
        base: "mega",
        variants: ["mega"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "radio",
        moji: "📻",
        unicode: "1f4fb",
        category: "objects",
        tags: [],
        link: null,
        base: "radio",
        variants: ["radio"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "vhs",
        moji: "📼",
        unicode: "1f4fc",
        category: "objects",
        tags: [],
        link: null,
        base: "vhs",
        variants: ["vhs"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "key",
        moji: "🔑",
        unicode: "1f511",
        category: "objects",
        tags: [],
        link: null,
        base: "key",
        variants: ["key"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "lock",
        moji: "🔒",
        unicode: "1f512",
        category: "objects",
        tags: [],
        link: null,
        base: "lock",
        variants: ["lock"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "bell",
        moji: "🔔",
        unicode: "1f514",
        category: "objects",
        tags: [],
        link: null,
        base: "bell",
        variants: ["bell"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "hole",
        moji: "🕳",
        unicode: "1f573",
        category: "objects",
        tags: [],
        link: null,
        base: "hole",
        variants: ["hole"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "black hard shell floppy disk",
        moji: "🖪",
        unicode: "1f5aa",
        category: "objects",
        tags: [],
        link: null,
        base: "black_hard_shell_floppy_disk",
        variants: ["black_hard_shell_floppy_disk"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "white hard shell floppy disk",
        moji: "🖫",
        unicode: "1f5ab",
        category: "objects",
        tags: [],
        link: null,
        base: "white_hard_shell_floppy_disk",
        variants: ["white_hard_shell_floppy_disk"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "document with text and picture",
        moji: "🖺",
        unicode: "1f5ba",
        category: "objects",
        tags: [],
        link: null,
        base: "document_with_text_and_picture",
        variants: ["document_with_text_and_picture"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "note",
        moji: "🗈",
        unicode: "1f5c8",
        category: "objects",
        tags: [],
        link: null,
        base: "note",
        variants: ["note"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "page",
        moji: "🗏",
        unicode: "1f5cf",
        category: "objects",
        tags: [],
        link: null,
        base: "page",
        variants: ["page"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "pages",
        moji: "🗐",
        unicode: "1f5d0",
        category: "objects",
        tags: [],
        link: null,
        base: "pages",
        variants: ["pages"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "moyai",
        moji: "🗿",
        unicode: "1f5ff",
        category: "objects",
        tags: [],
        link: null,
        base: "moyai",
        variants: ["moyai"],
        score: 117,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "grin",
        moji: "😁",
        unicode: "1f601",
        category: "faces",
        tags: [],
        link: null,
        base: "grin",
        variants: [
            "grin(p)",
            "grin(smiley)",
            "grin(wh)",
            "grin(dumpling)",
            "grin",
            "grin(ye)",
            "grin(br)",
            "grin(bk)",
            "grin(poop)",
            "grin(slime)",
            "grin(pudding)",
        ],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "smiley",
        moji: "😃",
        unicode: "1f603",
        category: "faces",
        tags: [],
        link: null,
        base: "smiley",
        variants: [
            "smiley(smiley)",
            "smiley(wh)",
            "smiley(ye)",
            "smiley(br)",
            "smiley",
            "smiley(p)",
            "smiley(bk)",
            "smiley(poop)",
            "smiley(slime)",
            "smiley(pudding)",
            "smiley(dumpling)",
        ],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "smile",
        moji: "😄",
        unicode: "1f604",
        category: "faces",
        tags: [],
        link: null,
        base: "smile",
        variants: [
            "smile(smiley)",
            "smile(wh)",
            "smile(ye)",
            "smile",
            "smile(p)",
            "smile(br)",
            "smile(bk)",
            "smile(poop)",
            "smile(slime)",
            "smile(pudding)",
            "smile(dumpling)",
        ],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "wink",
        moji: "😉",
        unicode: "1f609",
        category: "faces",
        tags: [],
        link: null,
        base: "wink",
        variants: [
            "wink(smiley)",
            "wink(wh)",
            "wink",
            "wink(ye)",
            "wink(p)",
            "wink(br)",
            "wink(bk)",
            "wink(poop)",
            "wink(slime)",
            "wink(pudding)",
            "wink(dumpling)",
        ],
        score: 1,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "smirk",
        moji: "😏",
        unicode: "1f60f",
        category: "faces",
        tags: [],
        link: null,
        base: "smirk",
        variants: [
            "smirk(smiley)",
            "smirk(wh)",
            "smirk",
            "smirk(ye)",
            "smirk(p)",
            "smirk(br)",
            "smirk(bk)",
            "smirk(poop)",
            "smirk(slime)",
            "smirk(pudding)",
            "smirk(dumpling)",
        ],
        score: 1,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "sweat",
        moji: "😓",
        unicode: "1f613",
        category: "faces",
        tags: [],
        link: null,
        base: "sweat",
        variants: [
            "sweat(smiley)",
            "sweat(wh)",
            "sweat",
            "sweat(ye)",
            "sweat(p)",
            "sweat(br)",
            "sweat(bk)",
            "sweat(poop)",
            "sweat(slime)",
            "sweat(pudding)",
            "sweat(dumpling)",
        ],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "angry",
        moji: "😠",
        unicode: "1f620",
        category: "faces",
        tags: [],
        link: null,
        base: "angry",
        variants: [
            "angry(smiley)",
            "angry(wh)",
            "angry(br)",
            "angry(bk)",
            "angry",
            "angry(ye)",
            "angry(p)",
            "angry(slime)",
            "angry(pudding)",
            "angry(poop)",
            "angry(dumpling)",
        ],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "rage",
        moji: "😡",
        unicode: "1f621",
        category: "faces",
        tags: [],
        link: null,
        base: "rage",
        variants: [
            "rage(wh)",
            "rage(ye)",
            "rage(p)",
            "rage(br)",
            "rage",
            "rage(poop)",
            "rage(slime)",
            "rage(pudding)",
            "rage(smiley)",
            "rage(dumpling)",
            "rage(bk)",
        ],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "weary",
        moji: "😩",
        unicode: "1f629",
        category: "faces",
        tags: [],
        link: null,
        base: "weary",
        variants: [
            "weary(ye)",
            "weary(wh)",
            "weary(br)",
            "weary(bk)",
            "weary",
            "weary(p)",
            "weary(poop)",
            "weary(slime)",
            "weary(pudding)",
            "weary(dumpling)",
            "weary(smiley)",
        ],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "sleepy",
        moji: "😪",
        unicode: "1f62a",
        category: "faces",
        tags: [],
        link: null,
        base: "sleepy",
        variants: [
            "sleepy(ye)",
            "sleepy(wh)",
            "sleepy(br)",
            "sleepy(bk)",
            "sleepy",
            "sleepy(p)",
            "sleepy(poop)",
            "sleepy(slime)",
            "sleepy(pudding)",
            "sleepy(smiley)",
            "sleepy(dumpling)",
        ],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "hushed",
        moji: "😯",
        unicode: "1f62f",
        category: "faces",
        tags: [],
        link: null,
        base: "hushed",
        variants: [
            "hushed(ye)",
            "hushed(smiley)",
            "hushed(wh)",
            "hushed(br)",
            "hushed(bk)",
            "hushed",
            "hushed(p)",
            "hushed(poop)",
            "hushed(slime)",
            "hushed(pudding)",
            "hushed(dumpling)",
        ],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "scream",
        moji: "😱",
        unicode: "1f631",
        category: "faces",
        tags: [],
        link: null,
        base: "scream",
        variants: [
            "scream(ye)",
            "scream(wh)",
            "scream(br)",
            "scream(bk)",
            "scream",
            "scream(p)",
            "scream(poop)",
            "scream(slime)",
            "scream(pudding)",
            "scream(smiley)",
            "scream(dumpling)",
        ],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "mask",
        moji: "😷",
        unicode: "1f637",
        category: "faces",
        tags: [],
        link: null,
        base: "mask",
        variants: [
            "mask(smiley)",
            "mask(ye)",
            "mask(wh)",
            "mask(br)",
            "mask(bk)",
            "mask(p)",
            "mask",
            "mask(poop)",
            "mask(slime)",
            "mask(pudding)",
            "mask(dumpling)",
        ],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "door",
        moji: "🚪",
        unicode: "1f6aa",
        category: "objects",
        tags: [],
        link: null,
        base: "door",
        variants: ["door"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "bath",
        moji: "🛀",
        unicode: "1f6c0",
        category: "objects",
        tags: [],
        link: null,
        base: "bath",
        variants: ["bath"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
    {
        code: "watch",
        moji: "⌚️",
        unicode: "231a",
        category: "objects",
        tags: [],
        link: null,
        base: "watch",
        variants: ["watch"],
        score: 0,
        r18: false,
        customizations: [],
        combinations: [],
    },
];
